#pragma once

#define X_LIST_START_COORD 280
#define Y_LIST_START_COORD 5
#define LIST_WIDTH 195
#define LIST_HIGHT 113

#define X_COPY_VALUE_START_COORD 280
#define Y_COPY_VALUE_START_COORD 115
#define COPY_VALUE_BUTTON_WIDTH 195
#define COPY_VALUE_BUTTON_HIGHT 20

#define X_EDIT_WIDTH 160
#define Y_EDIT_HIGHT 20

#define X_RECT_COLOR			5
#define Y_RECT_COLOR			5
#define X_RECT_MIX_COLOR_1		35
#define X_RECT_MIX_COLOR_2		35+150+100
#define X_RECT_MIX_COLOR_3		35+300+200
#define Y_RECT_MIX_COLOR_1		15
#define RECT_MIX_COLOR_WIDTH	150
#define RECT_MIX_COLOR_HIGHT	100
#define RECT_COLOR_WIDTH		90
#define RECT_COLOR_HIGHT		60
#define RECT_EDIT_MIX_WIDTH		50
#define RECT_EDIT_MIX_HIGHT		20

